name = "rabbit-hole"
main = "worker/index.js"
compatibility_date = "2026-06-28"

[vars]
FIREBASE_PROJECT_ID = "rabbit-hole-944d3"

[assets]
binding = "ASSETS"
directory = "./dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "rabbit-hole-db"
database_id = "3b298bab-fcb4-4e7b-96e7-a876e308ea97"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "rabbit-hole-media"
